apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app-sample
  name: app-sample
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-sample
    spec:
      containers:
        - image: boyander/app-sample
          imagePullPolicy: Always
          name: app-sample
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DBURL
              value: mongodb://app-mongo/bbdd
---
apiVersion: v1
kind: Service
metadata:
  name: app-sample-service
spec:
  type: NodePort
  selector:
    app: app-sample
  ports:
    - name: http
      port: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app-mongodb
  name: app-mongodb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app-mongodb
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-volume-claim
      containers:
        - image: mongo
          imagePullPolicy: Always
          name: mongo
          ports:
            - name: mongo
              containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: app-mongo
spec:
  type: ClusterIP
  selector:
    app: app-mongodb
  ports:
    - name: mongo
      port: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
